version: "3.8"

services:
  api:
    image: ghkdwldus0807/lead-me-recommend:latest
    container_name: recommender_server
    restart: unless-stopped
    env_file:
      - .env

    volumes:
      - ./app/models:/code/app/models

    ports:
      - "8000:8000"
